Source JUPITER_SWAP_URL from env
switchboard-xyz/switchboard pull request #30
Opened 2024-02-16 17:51 UTC by theelderbeever

Allows for the Jupiter swap url to be configured via an environment variable while defaulting to the original hardcoded value.

2024-03-04 18:31 UTC, abunsen commented
Can someone review?

2024-03-15 00:34 UTC, abunsen requested changes

2024-03-15 00:34 UTC, abunsen commented on rust/switchboard-utils/src/task/jupiter_swap.rs
> +            base_url = std::env::var("JUPITER_SWAP_URL").unwrap_or("https://public.jupiterapi.com/".to_string())
```suggestion
            base_url = std::env::var("JUPITER_SWAP_URL").unwrap_or("https://quote-api.jup.ag/v6/quote".to_string())
```

2024-03-15 00:34 UTC, abunsen commented on rust/switchboard-utils/README.md
> +- `JUPITER_SWAP_URL` - default: https://public.jupiterapi.com/
```suggestion
- `JUPITER_SWAP_URL` - for higher rate limits use: https://public.jupiterapi.com/
```

2024-03-15 00:48 UTC, theelderbeever commented on rust/switchboard-utils/src/task/jupiter_swap.rs
> +            base_url = std::env::var("JUPITER_SWAP_URL").unwrap_or("https://public.jupiterapi.com/".to_string())
Changed to `api.jup.ag/v6` since `/quote` is in the formatted string already.

2024-04-01 22:53 UTC, mgild approved these changes

2024-04-01 22:53 UTC, merged